# Generated by Django 4.2.3 on 2023-11-24 06:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgriLand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("gutno", models.IntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("gut", models.TextField()),
                ("crop", models.TextField()),
                ("owner", models.TextField()),
                ("remark", models.TextField()),
                ("village", models.TextField()),
                ("area", models.FloatField()),
                ("gut_no", models.TextField()),
            ],
            options={
                "db_table": "AgriLand",
                "managed": False,
            },
        ),
    ]
